#-------------------------------
# General Site Settings
#-------------------------------

# the subpath of your site, e.g. /blog
baseurl: "" 
baseurl_root: ""
# the base hostname & protocol for your site, e.g. http://example.com
url: "https://halla.ai" 

languages: ["ko", "en"]
# exclude_from_localizations: ["assets", "_sitemap.xml", "index.html", "404.html"]
default_locale_in_subfolder: false

#-------------------------------
# Build Settings
#-------------------------------

markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-maps
  - jekyll-multiple-languages-plugin

paginate: 6
paginate_path: "/page/:num"


#-------------------------------
# Collections
#-------------------------------

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /posts/:slug
  projects:
    output: true
    permalink: /projects/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  sass_dir: _sass
  style: compressed

# maps:
#   google:
#     api_key: # Your Google Maps API Key
