---
#-------------------------------
# Site Settings
title: 제주한라대학교 인공지능학과 (Department of Artificial Intelligence)
logo: "/assets/images/logo/logo-name.png"
logo_dark: "/assets/images/logo/logo-name-dark.png"
description: "제주한라대학교 인공지능학과 (Department of Artificial Intelligence, Cheju Halla University)"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.

#-------------------------------
# Author Settings
author_name: 제주한라대학교 (Cheju Halla University)

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "학과소개"
      url: "/about/"
    - title: "교수소개"
      url: "/faculty/"
    - title: "교과과정"
      url: "/curriculum/"
    # - title: "입학"
    #   url: "/admissions/"
    - title: "진로"
      url: "/career/"
    - title: "학생연구"
      url: "/projects/"
    - title: "정보광장"
      url: "/posts/"
    - title: "오시는길"
      url: "/location/"
      # submenu:
      # - url: "/contact/"
      #   title: "Contact"
    # - title: "게시판"
    #   url: "https://chu-ai.imweb.me/"

#-------------------------------
# Social Settings
social:
  - { icon: "fa-solid fa-building-columns", link: "https://www.chu.ac.kr" }
  - { icon: "fa-brands fa-youtube", link: "https://www.youtube.com/watch?v=8c9910JKf34" }
  # - { icon: "fa-brands fa-instagram", link: "https://instagram.com" }
  # - { icon: "fa-brands fa-github", link: "https://github.com" }
  - { icon: "fa-solid fa-comment-medical fa-bounce", link: "https://open.kakao.com/o/sgdkXqDg" }
  # - { icon: "icon-kakao-talk", link: "https://accounts.kakao.com" } # dark mode is not working

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: <span>인공지능학과</span> # Department of <span><i>Artificial Intelligence Engineering</i></span>, Cheju Halla University
  hero_description: 4차산업혁명으로 진화하는 미래산업사회에서 요구하는 인공지능, 빅데이터, 사이버보안, 사물인터넷 및 지능형 로봇 관련 차세대 핵심 전문기술인력 양성학과!!


  hero_image: "/assets/images/home/bg.png"
  hero_button_contact: 
  hero_button_about: 학과소개

#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Selected Projects

#-------------------------------
# Testimonials Section
section_testimonial_title: 🙂 What Students Say

testimonial_items:
  - name: "이규범"
    image: "/assets/images/testimonial/student-1.png"
    designation: "2024년 학생회장"
    link: "https://twitter.com/"
    content: "인공지능공학과는 현대 기술의 중심에 있는 분야로, 기초적인 컴퓨터 과학, 수학, 통계학, 머신러닝, 딥러닝 등의 이론을 토대로 혁신적인 인공지능 시스템을 설계, 개발, 최적화하는 학문을 탐구합니다. 이 과정에서 학생들은 데이터 분석, 패턴 인식, 자연어 처리, 컴퓨터 비전 등 다양한 분야에서의 문제 해결을 위한 알고리즘을 학습할 수 있습니다."

  - name: "양필성"
    image: "/assets/images/testimonial/student-2.png"
    designation: "21학번"
    link: "https://facebook.com/"
    content: "제주한라대학교 인공지능공학과는 최신 기술을 반영한 교육과정을 통해 학생들이 AI 분야에서 앞서 나갈 수 있도록 돕습니다. Chat GPT와 같은 대규모 언어 모델(LLM)을 다루는 실습을 통해 자연어 처리 능력을 키울 수 있으며, 컴퓨터 비전 분야에서의 다양한 프로젝트를 통해 시각 인공지능 기술을 심도 있게 배울 수 있습니다. 딥러닝과 데이터 처리 능력도 체계적으로 향상시킬 수 있어, 실무에 바로 적용 가능한 스킬을 습득할 수 있습니다. 인공지능에 대한 열정이 있다면, 제주한라대학교 인공지능공학과는 후회 없는 선택이 될 것입니다."

  - name: "김은지"
    image: "/assets/images/testimonial/student-3.png"
    designation: "2022년 학생회장"
    link: "https://twitter.com/"
    content: "제주한라대학교 인공지능공학과는 컴퓨터 비전, llm, Text-to-Image 등 다양한 주제에 대한 프로젝트를 진행할 수 있습니다. 최신 기술과 연구를 다루며, 학생들이 이론과 실습을 균형 있게 배울 수 있는 환경을 제공합니다. 또한, 전문 교수진과의 긴밀한 협업을 통해 깊이 있는 지식을 쌓고, 실제 문제 해결 능력을 키울 수 있습니다. 이러한 점에서 인공지능공학과는 인공지능 분야에 관심이 있는 학생들에게 최고의 선택이 될 것입니다."

#-------------------------------
# Blog Section
section_blog_title: 📚 Read Latest Posts
#-------------------------------

# Tags Section
section_tags_title: ✌️ Explore Topics

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: 인공지능학과 뉴스레터 구독
  mailchimp_identifier: halla.us21.list-manage.com/subscribe/post?u=2bb7450a6c4f2df4098555a00&amp;id=87dede211f&amp
  mailchimp_input_text: 이메일 주소를 입력해 주세요.
  mailchimp_background_image: /assets/images/mailchimp/subscribe-bg.png

#-------------------------------
# Footer Settings
footer_description: (63092) 제주특별자치도 제주시 한라대학로 38 <br>Tel. 064-741-7575 / Fax. 064-747-3989 <br>38 Halladaehak-ro, Jeju-si, Jeju Special Self-Governing Province, 63092 Republic of Korea <br>Tel. +82-64-741-7575 / Fax. +82-64-747-3989

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "학과소개"
      url: "/about/"
    - title: "교수소개"
      url: "/faculty/"
    - title: "교과과정"
      url: "/curriculum/"
    # - title: "입학"
    #   url: "/admissions/"
    - title: "진로"
      url: "/career/"
    - title: "리서치"
      url: "/projects/"
    - title: "정보광장"
      url: "/posts/"
    - title: "오시는길"
      url: "/location/"
    # - title: "게시판"
    #   url: "https://chu-ai.imweb.me/"

#-------------------------------
# Contact Settings
contact:
  email: yj.lee@chu.ac.kr # Add your form_id
  description: If you have any questions, please feel free to contact us.

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
# Add your shortname for Disqus Comment.
disqus_identifier: # halla-ai 

#-------------------------------
# Google Analytics
google_analytics: G-QP4FVB9F1X

#-------------------------------
# Giscus comments (RECOMMENDED)
# Follow instructions on https://giscus.app/ to setup for your repo to fill out
# the information below.
giscus:
  enable: true
  repo: chu-aie/.github # <your-github-user-name>/<your-github-repo-name>
  repo_id: R_kgDOKLOxpQ
  category: Comments # name of the category under which discussions will be created
  category_id: DIC_kwDOKLOxpc4CZjrm
  mapping: pathname
  strict: 0
  reactions_enabled: 1 # enable (1) or disable (0) emoji reactions
  input_position: top # whether to display input form below (bottom) or above (top) the comments
  theme: light # name of the color scheme
  emit_metadata: 0
  lang: ko
  loading: lazy # lazy, lazy-once, or immediate
